# Reproducible Research: Peer Assessment 1

## Loading and preprocessing the data
```{r loadingData,echo=TRUE} 
# Loading libraries
library(ggplot2)
library(plyr)
library(lattice)
# Data is loaded into a data frame called activity
activity <- read.csv("data/activity.csv")
# The NAs values are removed from activity
activityWithOutNAs <- na.omit(activity)
```

## What is mean total number of steps taken per day?
```{r meanTotalNumber,echo=TRUE}
#the histogram is made on the processed data (activity records without NAs), and grouped by 'date'
hist(rowsum(activityWithOutNAs[,'steps'], activityWithOutNAs[,'date']),
     breaks=50,col = "grey", main = 'Total number of steps taken each day (activity with out NAs') 
mean(activityWithOutNAs[,'steps'])
median(activityWithOutNAs[,'steps'])
```

## What is the average daily activity pattern?
```{r averageDailyActivity,echo=TRUE} 
# First of all, we calculate the steps of each interval, averaged across all days 
activityWONAsMeanStepsByDate <- ddply(activityWithOutNAs, "interval", summarise, mean.steps = mean(steps))
# And then, they are plot
ggplot(activityWONAsMeanStepsByDate) + geom_line(aes(interval, mean.steps),type = "l",colour="#000099") 
# 5-minute interval that contains the maximum number of steps
activityWONAsMeanStepsByDate[which.max(activityWONAsMeanStepsByDate[,'mean.steps']),]
```


## Imputing missing values
```{r imputtingMissingValues,echo=TRUE} 
# Number of rows with NAs
nrow(activity)-sum(complete.cases(activity))
# Strategy for filling the NA values: the mean for that 5-minute interval, calculated before
# Iteration over activity
for (i in 1:nrow(activity))  {
   # if the step value of the row is NA
   if (is.na(activity$steps[i])) 
       # the value 'mean.steps' from activityWONAsMeanStepsByDate that matches the intervals of both data frames is taken
       activity$steps[i] <- activityWONAsMeanStepsByDate$mean.steps[activityWONAsMeanStepsByDate$interval==activity[i,'interval']]
}

#the histogram is made on the original data which NA values had been filled
hist(rowsum(activity[,'steps'], activity[,'date']),
     breaks=50,col = "grey", main = 'Total number of steps taken each day (activity with NAs filled') 
mean(activity[,'steps'])
median(activity[,'steps'])
# The histogram has the same shape as the previous one. But the frecuencies are higher. This is becasue we increased the number of steps but with values that were averaged. So each 'bar' was increased in the same 'amount' of steps
```

## Are there differences in activity patterns between weekdays and weekends?
```{r activityPatterns,echo=TRUE} 
#First of all, we create a new factor variable in the by iterating over activity
for (i in 1:nrow(activity))  {
   activity$typeOfDay[i] <- ifelse(weekdays(as.Date(activity$date[i]))<"Saturday","weekday","weekend")
}
# Then, we calculate the steps of each interval, averaged across weekdays/weekends 
activityMeanStepsByTypeOfDay <- ddply(activity, .(interval, typeOfDay), summarise, mean.steps = mean(steps))
# And then, they are plot is drawn
xyplot(mean.steps ~ interval | typeOfDay, data=activityMeanStepsByTypeOfDay, pch=".",type="l", aspect=1, layout=c(2,1))
```